apiVersion: v1
kind: Service
metadata:
  name: littlesecrets
  namespace: littlesecrets
  labels:
    app: littlesecrets
spec:
  selector:
    app: littlesecrets
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
