apiVersion: v1
kind: Service
metadata:
  name: little-secrets
  namespace: little-secrets
  labels:
    app: little-secrets
spec:
  selector:
    app: little-secrets
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
